### ISSUE TITLE
Redirect to https localhost

### ISSUE THREAD

**Issue by paulvitic** [jshimko/meteor-launchpad#143]
I have build an image with name & tag *platform/latest* and appropriately declared ROOT_URL as "http://localhost:3000" in docker-compose. 

```
version: '3'

services:
    rabbitmq:
        build: ./rabbitmq
        volumes:
            - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
            - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
        ports: 
            - '5672:5672'
            - '15672:15672'
    mongodb:
        image: mongo
        ports:
            - '27017:27017'
    platform:
        image: platform:latest
        environment:
            - METEOR_SETTINGS
            - ROOT_URL=http://localhost:3000
            - MONGO_URL=mongodb://mongodb:27017/meteor
        ports:
            - '3000:3000'
        depends_on:
            - mongodb
            - rabbitmq
```

I also pass the meteor settings during docker-compose up as in
```
export METEOR_SETTINGS="$(cat path/to/settings.json)" && docker-compose up
```

When I try accessing the app from browser the response is a redirect to https://localhost

If i do docker exec -u 0 -it <container name> sh, then curl http://localhost:3000 I can see the meteor app running inside docker.

When I build the meteor app on my local machine in the same flow as the Dockerfile and run it locally with the same env variables and settings the application responds on http://localhost:3000 successfully.

Can anyone help please?
