### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by xwilders** [jshimko/meteor-launchpad#27]
I'm looking to incorporate testing into the build process.

At what point should the following command be run? I've forked this repository and tried adding it after meteor gets installed in build-meteor.sh, but the command seems to be ignored (the build succeeds but the logs show no trace of the tests running):

> meteor test --once --driver-package dispatch:mocha-phantomjs

**Comment by jshimko** [comment]
Testing isn't usually something you do inside your Docker image.  You should do that in a continuous integration workflow _before_ building the image.  Check out [CircleCI](https://CircleCI.com).

A Circle config might look something like this:

```yml
machine:
  node:
    version: 4.6.2
  services:
    - docker
  pre:
    - hash meteor 2>/dev/null || curl https://install.meteor.com | sh

dependencies:
  cache_directories:
    - "~/.meteor"
  override:
    - meteor npm install

test:
  override:
    - meteor test --once --driver-package dispatch:mocha-phantomjs

deployment:
  release:
    branch: master
    commands:
      - docker build -t yourorg/appname:latest .
      - docker login -e $DOCKER_EMAIL -u $DOCKER_USER -p $DOCKER_PASS
      - docker push yourorg/appname:latest
```
