### ISSUE TITLE
no such image using compose

### ISSUE THREAD

**Issue by QHose** [jshimko/meteor-launchpad#48]
hi,

I did not build or do anything yet, just put the dockerfile and the yml file in the project root. 
`FROM jshimko/meteor-launchpad:devbuild`

```
# docker-compose.yml

app:
  image: qhose/qrsmeteor:version0.1
  ports:
    - "80:3000"
  links:
    - mongo
  environment:
    - ROOT_URL=http://example.com
    - MONGO_URL=mongodb://mongo:27017/meteor

mongo:
  image: mongo:latest --storageEngine=wiredTiger 
```

I get this error
```
C:\Github\QRSMeteor (master)
λ docker-compose up -d
ERROR: no such image: mongo:latest+--storageEngine=wiredTiger: invalid reference format
```

if I do a pull its there:  `C:\Github\QRSMeteor (master)
λ docker pull mongo:latest
latest: Pulling from library/mongo
Digest: sha256:f1ae736ea5f115822cf6fcef6458839d87bdaea06f40b97934ad913ed348f67d
Status: Image is up to date for mongo:latest
`

**Comment by lidorcg** [comment]
I'm having the same problem after building

**Comment by jshimko** [comment]
I have no idea.  I've been using that docker-compose.yml format for years and have never had an issue.  Sounds like either Windows or Docker Compose isn't parsing the space between the `mongo:latest` and `--storageEngine=wiredTiger`.  It's not exactly a satisfying solution, but you can remove the `--storageEngine=wiredTiger` part if you want.  That's not fixing the issue, but it'll likely get around it. 

Other than that, I don't know what to tell you.  I don't ever get the same result on Mac or Linux.  If you can provide exact steps to reliably create the problem, I'd be happy to take a look.  But as it is, I can take your exact yml config (and switch the app image to something I have access to) and it runs every time.

**Comment by lidorcg** [comment]
for me it was solved like this:

```
mongo:
  image: mongo:latest
  command:
    - --storageEngine=wiredTiger
```

maybe it has something to do with docker-compose syntax versions...

**Comment by jshimko** [comment]
I updated the readme example to the more widely supported syntax.  Thanks for reporting the issue.

```yaml
# docker-compose.yml

app:
  image: yourname/app
  ports:
    - "80:3000"
  links:
    - mongo
  environment:
    - ROOT_URL=http://example.com
    - MONGO_URL=mongodb://mongo:27017/meteor

mongo:
  image: mongo:latest
  command: mongod --storageEngine=wiredTiger
```
