### ISSUE TITLE
exited with code 0 

### ISSUE THREAD

**Issue by mklueh** [jshimko/meteor-launchpad#53]
I´m trying to get my application running, but it terminates immediately and I cannot find a reason for that.

> myapplication | => Starting app on port 3000...
> myapplication exited with code 0

docker logs <containerId> just shows "exited with code 0"

How can I see what is going on within the container?

When go in the containers bash and start the application manually, it tells me it cannot reach the database. However, when I launch another docker container I can reach the database without any problems.
```

version: "3"
services:
  app:
    image: application:v0.0.3
    container_name: myapplication
    build:
        context: "."
    ports:
      - "80:3000"
    volumes:
      - "/application:/var/lib/application"
    environment:
      - MONGO_URL=mongodb://database:27017/meteor
      - DATA_DIRECTORY=/var/lib/application
      - ROOT_URL=http://localhost
    command: chmod a+rwx -R /var/lib/application

  database:
      image: mongo:3.0
      volumes:
        - "/application/db:/data/db:rw"
      command: mongod --smallfiles --quiet --logpath=/dev/null

networks:
  default:
    external:
      name: service-tier
```
